# ESPN display name -> CHN team name
ESPN_TO_CHN = {
    "Air Force Falcons": "Air Force",
    "Alaska Anchorage Seawolves": "Alaska-Anchorage",
    "Alaska Bulldogs": "Alaska",
    "Arizona State Sun Devils": "Arizona State",
    "Army Black Knights": "Army",
    "Assumption Falcons": None,  # not D1, skip
    "Augustana University (SD) Vikings": "Augustana",
    "Bemidji State Beavers": "Bemidji State",
    "Bentley Falcons": "Bentley",
    "Boston College Eagles": "Boston College",
    "Boston University Terriers": "Boston University",
    "Bowling Green Falcons": "Bowling Green",
    "Brown Bears": "Brown",
    "Canisius Golden Griffins": "Canisius",
    "Clarkson Golden Knights": "Clarkson",
    "Colgate Raiders": "Colgate",
    "Colorado College Tigers": "Colorado College",
    "Cornell Big Red": "Cornell",
    "Dartmouth Big Green": "Dartmouth",
    "Denver Pioneers": "Denver",
    "Ferris State Bulldogs": "Ferris State",
    "Harvard Crimson": "Harvard",
    "Holy Cross Crusaders": "Holy Cross",
    "Lake Superior State Lakers": "Lake Superior",
    "Lindenwood Lions": "Lindenwood",
    "Long Island University Long Island University": "Long Island",
    "Maine Black Bears": "Maine",
    "Massachusetts Minutemen": "Massachusetts",
    "Mercyhurst Lakers": "Mercyhurst",
    "Merrimack Warriors": "Merrimack",
    "Miami (OH) RedHawks": "Miami",
    "Michigan State Spartans": "Michigan State",
    "Michigan Tech Huskies": "Michigan Tech",
    "Michigan Wolverines": "Michigan",
    "Minnesota Duluth Bulldogs": "Minnesota-Duluth",
    "Minnesota Golden Gophers": "Minnesota",
    "Minnesota State Mavericks": "Minnesota State",
    "New Hampshire Wildcats": "New Hampshire",
    "Niagara Purple Eagles": "Niagara",
    "North Dakota Fighting Hawks": "North Dakota",
    "Northeastern Huskies": "Northeastern",
    "Northern Michigan Wildcats": "Northern Michigan",
    "Notre Dame Fighting Irish": "Notre Dame",
    "Ohio State Buckeyes": "Ohio State",
    "Omaha Mavericks": "Omaha",
    "Penn State Nittany Lions": "Penn State",
    "Princeton Tigers": "Princeton",
    "Providence Friars": "Providence",
    "Quinnipiac Bobcats": "Quinnipiac",
    "RIT Tigers": "RIT",
    "Rensselaer Engineers": "RPI",
    "Robert Morris Colonials": "Robert Morris",
    "Sacred Heart Pioneers": "Sacred Heart",
    "St. Cloud State Huskies": "St. Cloud State",
    "St. Lawrence Saints": "St. Lawrence",
    "St. Thomas - Minnesota Tommies": "St. Thomas",
    "Stonehill Stonehill": "Stonehill",
    "UConn Huskies": "Connecticut",
    "UMass Lowell  River Hawks": "Mass.-Lowell",
    "Union Dutchmen": "Union",
    "Vermont Catamounts": "Vermont",
    "Western Michigan Broncos": "Western Michigan",
    "Wisconsin Badgers": "Wisconsin",
    "Yale Bulldogs": "Yale",
}
